import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { elegante } from './constants/fonts';
import { BRIDE_BIODATA, GROOM_BIODATA } from './constants';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: `${GROOM_BIODATA.nickname} & ${BRIDE_BIODATA.nickname}`,
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} ${elegante.variable}`}>
				{children}
			</body>
		</html>
	);
}
